//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarieModele
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [JsonObject]
    [Serializable]
    [Table("discipline")]
    public partial class discipline
    {
        [Key]
        public int id_disciplina { get; set; }
        public string nume_disciplina { get; set; }
        [ForeignKey("cicluldestudii")]
        public int ciclul_de_studii { get; set; }
        [ForeignKey("programedestudiu")]
        public int program_de_studii { get; set; }
        [ForeignKey("anidestudiu")]
        public int anul_de_studiu { get; set; }
        public int semestrul { get; set; }
        public int nr_cursuri { get; set; }
        public int nr_laboratoare { get; set; }
        public int nr_seminare { get; set; }
        public int nr_intalniri_proiect { get; set; }
    
        public virtual anidestudiu anidestudiu { get; set; }
        public virtual cicluldestudii cicluldestudii { get; set; }
        public virtual programedestudiu programedestudiu { get; set; }
    }
}
