//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarieModele
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [JsonObject]
    [Serializable]
    [Table("programedestudiu")]
    public partial class programedestudiu
    {

        [Key]
        public int id_programe_de_studiu { get; set; }
        public string nume_programe_de_studiu { get; set; }
        [ForeignKey("cicluldestudii")]
        public int id_ciclul_de_studii { get; set; }
        public bool sters { get; set; }
        public virtual cicluldestudii cicluldestudii { get; set; }
    }
}
